#!/bin/bash

LIBRARYPATH="$HOME/.local/share/Steam"

read -p "Where is your steam library located? [${LIBRARYPATH}]: " custompath
: ${custompath:-$LIBRARYPATH}

echo "Recording path."
touch $HOME/.oneshot_linux_loc.txt
echo $LIBRARYPATH > $HOME/.oneshot_linux_loc.txt

echo "Patching oneshot in $LIBRARYPATH"

echo "Fix _______ app icon"
if [ -f $LIBRARYPATH/steamapps/common/OneShot/_______.png ]; then
	echo "Already installed"
else
	cp clover.png $LIBRARYPATH/steamapps/common/OneShot/_______.png
fi

echo "Installing fix_libs.sh"
if [ -f $LIBRARYPATH/steamapps/common/OneShot/fix_libs.sh ]; then
	echo "Already installed"
else
	cp fix_libs.sh $LIBRARYPATH/steamapps/common/OneShot/
	chmod +x $HOME/.local/share/Steam/steamapps/common/OneShot/fix_libs.sh
fi

# Fixed the intended way for the clover app to be accessed so the scripts will no longer be needed

echo "Fixing libraries"
cd $LIBRARYPATH/steamapps/common/OneShot/
sh fix_libs.sh
